# Generated by Django 3.0.6 on 2020-05-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=9.99, max_digits=100)),
                ('slug', models.SlugField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
